language: php

php:
    - 5.6
    - 7.0
before_script:
    #app composer required
    -  composer self-update
    -  composer install --no-interaction
 
script: 
    - phpunit --configuration phpunit.xml.dist --coverage-text

matrix:
  allow_failures:
    - php: 7.0

  fast_finish: true

notifications:
  # Whether to receive notifications from Travis
  email: false
